# Generated by Django 4.0.6 on 2022-07-17 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-data_create_post'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'Категория/статья', 'verbose_name_plural': 'Категории/статьи'},
        ),
        migrations.AlterField(
            model_name='author',
            name='author_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='author',
            name='rating_author',
            field=models.SmallIntegerField(default=0, verbose_name='Рейтинг автора'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_of_category',
            field=models.CharField(max_length=64, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='data_create_comment',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating_comment',
            field=models.SmallIntegerField(default=0, verbose_name='Рейтинг комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text_comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='news.PostCategory', to='news.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_create_post',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating_post',
            field=models.SmallIntegerField(default=0, verbose_name='Рейтинг статьи'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_post',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_post',
            field=models.CharField(max_length=64, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='vid',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='NW', max_length=2, verbose_name='Статья или Новость'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='category_through',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='post_through',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Статья'),
        ),
    ]
